--- !map:ActiveSupport::HashWithIndifferentAccess 

doc_introduction: 
  label: 
    de: Einleitung
    en: Introduction
doc_masks: 
  label: 
    de: Masken für Quellen
    en: Cataloging forms for sources
doc_tag_index: 
  label: 
    de: MARC Tag Index
    en: MARC tag index

################

doc_abbreviations: 
  label: 
    de: "Abkürzungen"
    en: Abbreviations
doc_abbr_dates: 
  label: 
    de: "Datierung"
    en: "Dates"
doc_abbr_general: 
  label: 
    de: "Allgemeine Abkürzungen und Begriffe"
    en: "General abbreviations and terms"
doc_abbr_keys: 
  label: 
    de: "Tonarten"
    en: "Keys"
doc_abbr_lang: 
  label: 
    de: "Sprachcodes"
    en: "Language codes"
doc_abbr_modes: 
  label: 
    de: "Kirchentonarten"
    en: "Ecclesiastical modes"
doc_abbr_voices_instr: 
  label: 
    de: "Stimmen- und Instrumentenbezeichnungen"
    en: "Terms for voices and instruments"

################

doc_aid: 
  label: 
    de: Arbeitshilfen
    en: Aide
doc_aid_liturgical_feasts: 
  label: 
    de: "Liturgische Feste"
    en: "Liturgical feasts"
doc_aid_locations: 
  label: 
    de: "Fundorte auf Quellen"
    en: "Locations on the source"
doc_aid_texts_sacred_works: 
  label: 
    de: "Standardtexte Sakralwerke"
    en: "Standard texts of sacred works"
doc_aid_titles_keywords: 
  label: 
    de: "Einordnungstitel - Schlagworte"
    en: "Standardised titles - Subject headings"
doc_aid_transposing_instruments: 
  label: 
    de: "Hilfe zur Transponierung von Instrumenten"
    en: "Help for transposing instruments"    

################

doc_cataloguing: 
  label: 
    de: Allgemeine Erfassung Hilfe
    en: General cataloguing guidelines
doc_cat_collections: 
  label: 
    de: Erfassung von Sammlungen
    en: Cataloging collection and convoluta
doc_cat_templates: 
  label: 
    de: Templates
    en: Templates
doc_cat_authorities: 
  label: 
    de: Autoritäten
    en: Authorities

################

doc_editor: 
  label: 
    de: "Editor Hilfe"
    en: Editor help
doc_edit_functions: 
  label: 
    de: "Grundsätzliche Funktionen"
    en: Basic functions
doc_edit_workflow: 
  label: 
    de: "Workflow"
    en: Workflow

################

"000": 
  label: 
    it: Leader
    fr: Guide
    de: Leader
    en: Leader
"001": 
  label: 
    it: Numero documento RISM
    fr: No. RISM
    de: RISM Dokumentnummer
    en: RISM ID No.
"003": 
  label: 
    it: Identificatore del numero di controllo
    fr: "Identité du numéro de contrôle"
    de: Kontrollnummer-Bezeichnung
    en: Control number identifier
"506": 
  label: 
    it: Restrizioni all'accesso
    fr: Restriction d'accès
    de: "Zugangsbeschränkungen"
    en: Access restriction
  fields: 
    a: 
      label: 
        it: Restrizioni all'accesso
        fr: Restriction d'accès
        de: "Zugangsbeschränkungen"
        en: Access restriction
      edit_label: 
        en: ""
"541": 
  label: 
    it: Fonte immediata d'acquisto
    fr: Source d'acquisition
    de: Unmittelbare Beschaffungsquelle
    en: Source of acquisition
  fields: 
    a: 
      label: 
        it: Nota sulla fonte d'acquisto
        fr: Source d'acquisition
        de: Beschaffungsquelle
        en: Source of acquisition note
    c: 
      label: 
        it: Metodo d'acquisto
        fr: "Méthode d'acquisition"
        de: Beschaffungsart
        en: Method of acquisition
    d: 
      label: 
        it: Data d'acquisto
        fr: Date d'acquisition
        de: Beschaffungsdatum
        en: Date of acquisition
    e: 
      label: 
        it: Numero di acquisizione
        fr: Numéro d'acquisition
        de: Akzessionsnumer
        en: Accession number
"561": 
  label: 
    it: Provenienza
    fr: Provenance
    de: Herkunft der Quelle
    en: Provenance
  fields: 
    a: 
      label: 
        it: Provenienza
        fr: Provenance
        de: Herkunft der Quelle
        en: Provenance
      edit_label: 
        en: ""
"591": 
  label: 
    it: Altra segnatura
    fr: Autre cote
    de: Weitere Signatur
    en: Other shelf number
  fields: 
    a: 
      label: 
        it: Altra segnatura
        fr: Autre cote
        de: Weitere Signatur
        en: Other shelf number
"852": 
  label: 
    it: Sigla della biblioteca
    fr: "Sigle de bibliothèque"
    de: Bibliothekssigel
    en: Library siglum
  fields: 
    a: 
      label: 
        it: Sigla della biblioteca
        fr: "Sigle de bibliothèque"
        de: Bibliothekssigel
        en: Library siglum
    b: 
      label: 
        it: Dipartimento
        fr: Section
        de: Abteilung
        en: Sublocation
    c: 
      label: 
        it: Segnatura
        fr: Cote
        de: Signatur
        en: Shelfmark
    d: 
      label: 
        it: Segnatura vecchia (olim)
        fr: Ancienne cote (olim)
        de: Alte Signatur (olim)
        en: Former shelf mark
    q: 
      label: 
        it: Materiale conservato
        fr: "Matériau préservé"
        de: Erhaltenes Material
        en: Preserved Parts
    z: 
      label: 
        it: Osservazioni
        fr: Remarque
        de: Bemerkungen
        en: Note
    e: 
      label: 
        it: Biblioteca
        fr: "Bibliothèque"
        de: Bibliothek
        en: Library
"856": 
  label: 
    it: Localizzazione e accesso elettronico
    fr: "Ressource électronique externe"
    de: Elektronische Lokalisierung und Zugriff
    en: External resource
  fields: 
    z: 
      label: 
        it: Nota destinata al pubblico
        fr: Remarque sur la ressource externe
        de: "Für das Publikum bestimmte Fussnote"
        en: Note about external resource
    u: 
      label: 
        it: Risorsa esterna
        fr: Ressource externe
        de: Uniform Resource Identifier
        en: External resource
    x: 
      label: 
        it: Tipo di collegamento
        fr: Type de lien
        de: Art der Verlinkung
        en: Link type
added_entry: 
  label: 
    it: Note secondarie
    fr: "Entrées secondaires"
    de: Nebeneintragungen
    en: Added entry fields
added_entries: 
  label: 
    it: Nomi secondari
    fr: Noms secondaires
    de: Nebeneintragungen
    en: Added entry name
added_series: 
  label: 
    it: Note secondarie sul titolo generale
    fr: "Entrées de collection"
    de: Nebeneintragungen Gesamttitel
    en: Series added entry fields
administration: 
  label: 
    it: Amministrazione
    fr: Administration
    de: Administration
    en: Administration
arr: 
  label: 
    it: Arrangiatore
    fr: Arrangeur
    de: Bearbeiter
    en: Arranger
art: 
  label: 
    it: Scenografo
    fr: "Metteur en scène"
    de: "Bühnenbildner"
    en: Artist
asn: 
  label: 
    it: Altro nome
    fr: Autre nom
    de: Weiterer Name
    en: Associated name
aut: 
  label: 
    it: Autore
    fr: Auteur
    de: Autor
    en: Author
bibliographical_reference: 
  label: 
    it: Bibliografia
    fr: "Références"
    de: Literatur
    en: References
bnd: 
  label: 
    it: Rilegatore
    fr: Relieur
    de: Buchbinder
    en: Binder
bsl: 
  label: 
    it: Libraio musicale
    fr: Libraire
    de: "Musikalienhändler"
    en: Bookseller
ccp: 
  label: 
    it: Autore della fonte letteraria
    fr: Auteur du texte
    de: Autor der Textvorlage
    en: Conceptor
chr: 
  label: 
    it: Coreografo
    fr: "Chorégraphe"
    de: Choreograph
    en: Choreographer
clb: 
  label: 
    it: Autore secondario
    fr: Collabarateur
    de: Mitverfasser
    en: Collaborator
cmp: 
  label: 
    it: Compositore/Compositore secondario
    fr: Compositeur / Co-compositeur
    de: Komponist / Mitkomponist
    en: Composer
cnd: 
  label: 
    it: Direttore d'orchestra
    fr: Chef d'orchestre
    de: Dirigent
    en: Conductor
cns: 
  label: 
    it: Censore
    fr: Censeur
    de: Zensor
    en: Censor
codes: 
  label: 
    it: Numeri e codici
    fr: "Numéros et codes"
    de: Nummern und Codes
    en: Numbers and code fields
com: 
  label: 
    it: Compilatore
    fr: Compilateur
    de: Kompilator
    en: Compiler
content: 
  label: 
    it: Descrizione del contenuto
    fr: Description du contenu
    de: Inhaltsangaben
    en: Content description
control: 
  label: 
    fr: "Champs de contrôle"
    de: Kontrollfelder
    ot: Campi di controllo
    en: Control Fields
cst: 
  label: 
    it: Costumista
    fr: Costumier
    de: "Kostümbildner"
    en: Costume designer
date: 
  label: 
    it: Date
    fr: Dates
    de: Daten
    en: Dates
description: 
  label: 
    it: Campi per la descrizione fisica
    fr: "Description matérielle"
    de: "Felder für die physische Beschreibung"
    en: Physical description, etc. fields
diplomatic_title: 
  label: 
    it: Titolo diplomatico
    fr: Titre diplomatique
    de: Diplomatischer Titel
    en: Diplomatic title
dnc: 
  label: 
    it: Ballerino
    fr: Danceur
    de: "Tänzer"
    en: Dancer
dnr: 
  label: 
    it: Donatore
    fr: Donateur
    de: Donator
    en: Donor
dte: 
  label: 
    it: Dedicatario
    fr: "Dédicataire"
    de: "Widmungsträger"
    en: Dedicatee
dub: 
  label: 
    it: Dubbio
    fr: Douteux
    de: Zweifelhaft
    en: Dubious
edition: 
  label: 
    it: Campi per i dati editoriali
    fr: Edition, adresse bibliographique, etc.
    de: Ausgabe- und Impressumsfelder
    en: Edition, imprint, etc. fields
edt: 
  label: 
    it: Curatore
    fr: Editeur
    de: Herausgeber
    en: Editor
egr: 
  label: 
    it: Incisore
    fr: Graveur
    de: Stecher
    en: Engraver
fmo: 
  label: 
    it: Proprietario precedente
    fr: "Propriétaire précédent"
    de: Vorbesitzer
    en: Former owner
holding: 
  label: 
    it: Informazioni sul fondo
    fr: "Données bibliographiques, fonds, etc."
    de: Bestandsdaten
    en: Holdings, location, etc. fields
ill: 
  label: 
    it: Disegnatore
    fr: Illustrateur
    de: Illustrator
    en: Illustrator
incipit: 
  label: 
    it: Incipit
    fr: Incipits
    de: Incipits
    en: Incipits
itr: 
  label: 
    it: Strumentista
    fr: Instrumentiste
    de: Instrumentalist
    en: Instrumentalist
lbt: 
  label: 
    it: Librettista
    fr: Librettiste
    de: Librettist
    en: Librettist
library: 
  label: 
    it: Biblioteca
    fr: "Bibliothèque"
    de: Besitzerangaben
    en: Library information
linkage: 
  label: 
    it: Collegamento
    fr: Liens
    de: Verlinkung
    en: Linkage
linking: 
  label: 
    it: Note su collegamenti
    fr: "Entrées de liens"
    de: "Verknüpfungseintragungen"
    en: Linking entry fields
ltg: 
  label: 
    it: Litografo
    fr: Litographe
    de: Lithograph
    en: Lithograph
lyr: 
  label: 
    it: Poeta
    fr: Parolier
    de: Textdichter
    en: Lyricist
main: 
  label: 
    it: Campi principali
    fr: "Entrées principales"
    de: Haupteintragungen
    en: Exemplar
notes: 
  label: 
    it: Note
    fr: Notes
    de: Fussnoten
    en: Note fields
unmatched: 
  label: 
    it: Campi sconoscuti
    fr: Champs non reconnus
    de: Unbekannte Felder
    en: Unknown fields
otm: 
  label: 
    it: Organizzatore
    fr: Organisateur
    de: Veranstalter
    en: Event organizer
pat: 
  label: 
    it: Committente
    fr: "Mécène"
    de: "Mäzen/Auftraggeber"
    en: Patron
pbl: 
  label: 
    it: Editore
    fr: Editeur
    de: Verleger
    en: Publisher
performance: 
  label: 
    it: Rappresentazioni
    fr: Performances
    de: "Aufführungen"
    en: Performances
physical_description: 
  label: 
    it: Descrizione fisica
    fr: "Description physique"
    de: Physische Beschreibung
    en: Physical description
material_description: 
  label: 
    it: Descrizione del materiale
    fr: "Description du matériel"
    de: Materialbeschreibung
    en: Material description    
ppm: 
  label: 
    it: Fabbricante di carta
    fr: Papetier
    de: Papierhersteller
    en: Paper maker
prd: 
  label: 
    it: Personale alla produzione
    fr: "Personnel de réalisation"
    de: Produktionspersonal
    en: Production personnel
prf: 
  label: 
    it: Interprete
    fr: "Interprète"
    de: Interpret
    en: Performer
provenance: 
  label: 
    it: Provenienza
    fr: Provenance
    de: Provenienz
    en: Provenance
prt: 
  label: 
    it: Stampatore
    fr: Imprimeur
    de: Drucker
    en: Printer
scr: 
  label: 
    it: Copista
    fr: Scribe
    de: Schreiber
    en: Scribe
series: 
  label: 
    it: Informazioni sul titolo generale
    fr: Mentions de collection
    de: Gesamttitelangaben
    en: Series statement fields
show_admin: 
  label: 
    it: Amministrazione
    fr: Administration
    de: Administration
    en: Administration
show_content: 
  label: 
    it: Contenuto
    fr: Contenu
    de: Inhalt
    en: Content
show_details: 
  label: 
    it: Descrizione fisica
    fr: "Détail de la source"
    de: Physische Beschreibung
    en: Source details
show_distribution: 
  label: 
    it: Organico
    fr: Formation
    de: Besetzung
    en: Distribution
show_information: 
  label: 
    it: Note
    fr: "Information supplémentaire"
    de: Anmerkungen
    en: Further information
show_library: 
  label: 
    it: Biblioteca
    fr: "Bibliothèque"
    de: Besitzerangaben
    en: Library information
show_links: 
  label: 
    it: Titoli connessi
    fr: Titres connexes
    de: Verlinkungen
    en: Related Titles
show_material: 
  label: 
    it: Descrizione del materiale
    fr: "Description du matériel"
    de: Materialbeschreibung
    en: Material description     
show_references: 
  label: 
    it: Bibliografia
    fr: "Références"
    de: Literatur
    en: References
show_resources: 
  label: 
    it: Collegamenti
    fr: Liens
    de: Links
    en: Related resources
show_summary: 
  label: 
    it: Riassunto
    fr: "Résumé"
    de: Zusammenfassung
    en: Summary
show_terms: 
  label: 
    it: Descrittori
    fr: Termes
    de: Deskriptoren
    en: Index terms
subject: 
  label: 
    it: Note sul sitolo uniforme
    fr: "Entrées de sujets"
    de: Schlagworteintragungen
    en: Subject access fields
title: 
  label: 
    it: Titolo e campi correlati
    fr: "Titre et champs associés"
    de: Titel- und damit verbundene Felder
    en: Title and title-related fields
trl: 
  label: 
    it: Traduttore
    fr: Traducteur
    de: "Übersetzer"
    en: Translater
voc: 
  label: 
    it: Cantante
    fr: Vocaliste
    de: "Sänger"
    en: Vocalist
